# Generated by Django 4.2.13 on 2024-06-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0007_alter_ship_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipRoutePoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OAuth.ship')),
            ],
        ),
    ]
