# Generated by Django 4.2.13 on 2024-06-14 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0009_shiproutepoint_direction_shiproutepoint_next_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiproutepoint',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OAuth.ship'),
        ),
        migrations.CreateModel(
            name='EditShipView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edittime', models.DateTimeField(auto_now=True)),
                ('shipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OAuth.ship')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditShipPointView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edittime', models.DateTimeField(auto_now=True)),
                ('pointid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OAuth.shiproutepoint')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
