# Generated by Django 4.2.13 on 2024-06-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0011_editshipview_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editshippointview',
            old_name='pointid',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='editshippointview',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='editshipview',
            old_name='shipid',
            new_name='ship',
        ),
        migrations.RenameField(
            model_name='editshipview',
            old_name='userid',
            new_name='user',
        ),
    ]
