# Generated by Django 4.2.13 on 2024-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0016_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiproutepoint',
            name='direction',
            field=models.FloatField(null=True),
        ),
    ]
